[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# assets 폴더는 직접 제공 (리다이렉트 안함)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# 나머지 모든 요청은 SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 30명 동시 접속을 위한 성능 최적화
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 보안 강화
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://*.firebaseio.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.firebaseio.com wss://*.firebaseio.com https://*.googleapis.com;"

# Firebase 및 API 호출 최적화
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

# 실시간 리더보드를 위한 WebSocket 지원
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"